name: khmerscan
description: Modern document scanner for Cambodia from KhmerLens
version: 1.0.2+4
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core functionality

  path_provider: ^2.1.0
  path: ^1.8.3
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  uuid: ^4.0.0
  image: ^4.1.3

  # Sharing & Export
  share_plus: ^12.0.1
  pdf: ^3.10.7
  printing: ^5.11.1

  # AdMob
  google_mobile_ads: ^7.0.0

  # Modern UI
  flutter_staggered_grid_view: ^0.7.0
  iconify_flutter: ^0.0.7
  flutter_slidable: ^4.0.3
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  reorderable_grid_view: ^2.2.8

  # Utils
  provider: ^6.1.0
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0

  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  permission_handler: ^12.0.1
  in_app_review: ^2.0.11
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.1
  firebase_performance: ^0.11.1
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  flutter_local_notifications: ^20.0.0
  flutter_hooks: ^0.21.3+1
  cunning_document_scanner: ^1.4.0
  mobile_scanner: ^7.1.4
  openfoodfacts: ^3.0.0
  http: ^1.2.0
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_text_recognition: ^0.15.1
  nutrition_ai: ^3.2.14
  bloc_concurrency: ^0.3.0
  flutter_tesseract_ocr:
    path: packages/flutter_tesseract_ocr
  webview_flutter: ^4.13.1
  firebase_auth: ^6.1.4
  file_picker: ^10.3.10
  pdf_render: ^1.4.7
  archive: ^4.0.7
  xml: ^6.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/icon/
    - assets/tessdata/
    - assets/tessdata_config.json

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/foreground.png"